### ISSUE TITLE
send incline data from unity

### ISSUE THREAD

**Issue by unitylab-dev** [DaveBsns/SimulatorRaspberry#12]
send the current tilt in unity over UDP. value between -20 to 20 in 0.5 steps is needed.

unity_values["bleTilt"]
like 
unity_values["bleFan"]

**Comment by marc-hessenauer** [comment]
files to edit
/Users/marchessenauer/techstuff/unity/BicycleSimulator/Assets/Functional/UDPReceive/BikeDataSO.cs
/Users/marchessenauer/techstuff/unity/BicycleSimulator/Assets/Functional/UDPReceive/UdpSender.cs
/Users/marchessenauer/techstuff/unity/BicycleSimulator/Assets/Road Users/Simple Bicycle Physics/Scripts/BiycleController.cs

**Comment by marc-hessenauer** [comment]
Purpose: Transfer the data for the Incline from Unity to the venv in order to adjust the Elite Rizer.

As suggested via WhatsApp, I will name the variable bleIncline

**Comment by marc-hessenauer** [comment]
@PSenfft Please describe what exactly the JSON you expect is supposed to look like

**Comment by marc-hessenauer** [comment]
Adjusted UdpSender as follows:
string jsonString = "{\"bleFan\":" + dataToSend + ", \"bleIncline\":-10}";

**Comment by marc-hessenauer** [comment]
@PSenfft I assume that negative values lower the rizer and vice versa?

**Comment by marc-hessenauer** [comment]
Data is sent like this: {"bleFan":0, "bleIncline": -1}

**Comment by marc-hessenauer** [comment]
@PSenfft please check and give feedback if values need to be adjusted

**Comment by unitylab-dev** [comment]
is the incline data just in the UdpReceiver Scene or in both scenes? Because the Udo Scene doesnt work on the labor PC (prefab instance probleme).

**Comment by marc-hessenauer** [comment]
Data has this format, as logged in the Unity console: {"bleFan":0, "bleIncline": -0.5}

Validated online here: https://jsonlint.com/

Please check what arrives in UDP and suggest changes to the structure if necessary

**Comment by unitylab-dev** [comment]
> send the current tilt in unity over UDP. value between -20 to 20 in 0.5 steps is needed.
> 
> unity_values["bleTilt"] like unity_values["bleFan"]

its just +20 to -10

**Comment by marc-hessenauer** [comment]
changed to int values from -20 to +40
