### ISSUE TITLE
Scenario 1 Implementation Draft

### ISSUE THREAD

**Issue by marc-hessenauer** [DaveBsns/SimulatorRaspberry#3]
- create a draft of the city map
- include planned movement of the cyclist
- indcate which Unity assets (roadsigns, scenery, road details) are missing

**Comment by marc-hessenauer** [comment]
Scenario 1: Easy ride in the city
* Good weather
* Bicycle lane is free
* Cars keep their distance
* Cars don’t drive too fast
* Intersection with a red light that the cyclist crosses straight 
* Right turn without a traffic light and Stop sign
* During the day
* Covers 17 Use Case Actions

**Comment by marc-hessenauer** [comment]
![image](https://github.com/DaveBsns/SimulatorRaspberry/assets/114930207/55fbdc71-f629-4e9c-82f3-da96c3476f5c)
first draft

**Comment by DaveBsns** [comment]
So the purpose of this scenario is that the bicycle rider will use the Bicycle lane on the right side of the road, right?
I really like the scenario, go ahead! :)

**Comment by marc-hessenauer** [comment]
yes it is - thanks for the feedback!

**Comment by marc-hessenauer** [comment]
done
