### ISSUE TITLE
Fix Vorfahrt gewähren sign

### ISSUE THREAD

**Issue by marc-hessenauer** [DaveBsns/SimulatorRaspberry#36]
shape of front and back doesn't align - please check, I didn't get it to work unfortunately

**Comment by marc-hessenauer** [comment]
Object is called giveWaySign in scenario 3. on the threewayintersection under Roadside Decoration

**Comment by PhilippBau** [comment]
Issues fixed - solution: use quad not cube as GameObject base for Sign
