### ISSUE TITLE
Don't turn camera when steering

### ISSUE THREAD

**Issue by unitylab-dev** [DaveBsns/SimulatorRaspberry#6]
Currently the camera moves with the direction of the bicycle, even when the head with the VR Headset is still

**Comment by marc-hessenauer** [comment]
Setting to edit: Road Users > VRBicycle Start > [CameraRig] > Object Follower > Object To Follow

**Comment by marc-hessenauer** [comment]
was re-evaluated and is now closed due to low priority. parameter given above was already set to a suitable property
